# GitHub Pages
### ### ### ### ### ###

github: [metadata]                          # set by GitHub Pages, can be overwritten
#lsi: false                                 # set by GitHub Pages, cannot be changed
#safe: true                                 # set by GitHub Pages, cannot be changed
#source: [your repo's top level directory]  # set by GitHub Pages, cannot be changed
#incremental: false                         # set by GitHub Pages, cannot be changed
#highlighter: rouge                         # set by GitHub Pages, cannot be changed
#gist:
#  noscript: false                          # set by GitHub Pages, cannot be changed
kramdown:
  input: GFM                                # set by GitHub Pages, can be overwritten
  hard_wrap: false                          # set by GitHub Pages, can be overwritten
#  math_engine: mathjax                     # set by GitHub Pages, cannot be changed
gems:
  - jekyll-coffeescript                     # set by GitHub Pages, can be overwritten
  - jekyll-paginate                         # set by GitHub Pages, can be overwritten

# Jekyll settings
### ### ### ### ### ###

encoding: utf-8
strict_front_matter: true
excerpt_separator: <!--more-->
exclude:
  - CNAME
  - docker-compose.yml
  - LICENSE
  - README.md
  - _tools/_draft.md
webrick:
  headers:
    X-Powered-By: PHP/6

# PHP QA
### ### ### ### ### ###

author: Bart Reunes   
name: PHP Quality Assurance Tools
description: A list of PHP Quality Assurance Tools
url: //phpqa.io

title: PHP Quality Assurance Tools
subtitle: Looking for tools to make your PHP code even better? Dive right into the exciting world of PHP QA!

google_analytics: UA-100482560-1
disqus: phpqa

collections:

  pages:
    output: true
    permalink: /:title.html

  tools:
    output: true
    permalink: /:collection/:title.html

  posts:
    output: true
    permalink: /:collection/:categories/:year/:month/:day/:title.html

navigation:
  - { label: Tools,                   icon: fa-cogs,            url: /                                                      }
  - { label: Usage,                   icon: fa-magic,           url: /usage                                                 }
  - { label: News,                    icon: fa-list-alt,        url: /news                                                  }
  - { label: About,                   icon: fa-info-circle,     url: /about                                                 }
  - { label: Contact,                 icon: fa-sign-language,   url: 'https://github.com/phpqa/phpqa.github.io/issues'      }

sidebar:
  - { label: Static Analysis Tools,   icon: fa-list-ol,         url: 'https://github.com/exakat/php-static-analysis-tools'  }
  - { label: PHP The Right Way,       icon: fa-thumbs-o-up,     url: 'http://www.phptherightway.com/'                       }
  - { label: PHP The Wrong Way,       icon: fa-thumbs-o-down,   url: 'http://www.phpthewrongway.com/'                       }
  - { label: PHP.UserGroup,           icon: fa-users,           url: 'http://php.ug/'                                       }
  - { label: PHP Women,               icon: fa-venus,           url: 'http://phpwomen.org/'                                 }
  - { label: PHP Mentoring,           icon: fa-graduation-cap,  url: 'https://php-mentoring.org/'                           }
  - { label: OSMI,                    icon: fa-handshake-o,     url: 'https://osmihelp.org/'                                }

metadata:
  authors:      { label: Author(s),           icon: fa-user,            multiple: true                              }
  website:      { label: Website,             icon: fa-globe,           button: true,   button-class: btn-website   }
  license:      { label: License,             icon: fa-id-card                                                      }
  terms:        { label: Terms (Of Service),  icon: fa-thumbs-o-up,     button: true,   button-class: btn-terms     }
  wiki:         { label: Wiki,                icon: fa-list-alt,        button: true,   button-class: btn-wiki      }
  docs:         { label: Documentation,       icon: fa-info,            button: true,   button-class: btn-docs      }
  demo:         { label: Demo,                icon: fa-desktop,         button: true,   button-class: btn-demo      }
  source:       { label: Source,              icon: fa-code,            button: true,   button-class: btn-source    }
  packagist:    { label: Packagist,           icon: fa-compass,         button: true,   button-class: btn-packagist }
  docker:       { label: Docker,              icon: fa-ship,            button: true,   button-class: btn-docker    }
  command:      { label: Command,             icon: fa-terminal                                                     }
  dependencies: { label: Dependencies,        icon: fa-check-square-o,  multiple: true                              }
