# GitHub Pages
### ### ### ### ### ###

github: [metadata]                                    # set by GitHub Pages, can be overwritten
#lsi: false                                           # set by GitHub Pages, cannot be changed
#safe: true                                           # set by GitHub Pages, cannot be changed
#source: [your repo's top level directory]            # set by GitHub Pages, cannot be changed
#incremental: false                                   # set by GitHub Pages, cannot be changed
#highlighter: rouge                                   # set by GitHub Pages, cannot be changed
#gist:
#  noscript: false                                    # set by GitHub Pages, cannot be changed
kramdown:
  input: GFM                                          # set by GitHub Pages, can be overwritten
  hard_wrap: false                                    # set by GitHub Pages, can be overwritten
#  math_engine: mathjax                               # set by GitHub Pages, cannot be changed
  smart_quotes: ["apos", "apos", "quot", "quot"]      # turn off smart quotes
plugins:
  - jekyll-coffeescript                               # set by GitHub Pages, can be overwritten
  - jekyll-paginate                                   # set by GitHub Pages, can be overwritten
  - jekyll-seo-tag                                    # add seo tag
  - jekyll-sitemap                                    # add sitemap
  - jekyll-feed                                       # add rss feed

# Jekyll settings
### ### ### ### ### ###

encoding: utf-8
strict_front_matter: true
excerpt_separator: <!--more-->
exclude:
  - CNAME
  - docker-compose.yml
  - LICENSE
  - README.md
  - _projects/_draft.md
webrick:
  headers:
    X-Powered-By: PHP/6

# PHP QA
### ### ### ### ### ###

author: Bart Reunes   
name: PHP Quality Assurance
description: A community managed website about PHP Quality Assurance
url: https://phpqa.io
lang: en_US

title: PHP Quality Assurance
subtitle: Looking for ways to make your PHP code even better? Find the projects that can help you!

google_analytics: UA-100482560-1

webmaster_verifications:
  google: JITUi06ndisXmR9iEyEtJWMR7ZaYF8ycjhUTUvubBHk
  bing: 3CB22B04462C70550E27942615BF8C01

collections:

  pages:
    output: true
    permalink: /:title.html

  projects:
    output: true
    permalink: /:collection/:title.html

  posts:
    output: true
    permalink: /:collection/:categories/:year/:month/:day/:title.html


navigation:
  projects:     { label: Projects,      icon: fas fa-cogs,              url: /index.html                                  }
  community:    { label: Websites,      icon: fas fa-map-signs,         url: /websites.html                               }
  about:        { label: About,         icon: fas fa-info-circle,       url: /about.html                                  }
  news:         { label: News,          icon: fas fa-list-alt,          url: /news.html                                   }
  #usage:        { label: Usage,         icon: fas fa-magic,             url: /usage.html                                  }
  github:       { label: GitHub,        icon: fab fa-github,            url: 'https://github.com/phpqa/phpqa.github.io'   }
  dockerhub:    { label: DockerHub,     icon: fab fa-docker,            url: 'https://hub.docker.com/u/phpqa/'            }
  contributing: { label: Contributing,  icon: fas fa-sign-language,     url: /contributing.html                           }

links:
  - { label: PHP.net Manual,            icon: far fa-bookmark,          url: 'https://secure.php.net/manual/en/',                   description: 'PHP.net Manual'                                                                         }
  - { label: PHP Internals Book,        icon: fas fa-book,              url: 'http://www.phpinternalsbook.com/',                    description: 'A collaborative effort to better document and describe how PHP works internally.'       }
  - { label: PHP The Right Way,         icon: far fa-thumbs-up,         url: 'http://www.phptherightway.com/',                      description: 'Quick reference for PHP popular coding standards.'                                      }
  - { label: PHP The Wrong Way,         icon: far fa-thumbs-down,       url: 'http://www.phpthewrongway.com/',                      description: 'A pragmatic view on PHP programming.'                                                   }
  - { label: PHP does not suck,         icon: fas fa-certificate,       url: 'https://phpdoesnotsuck.herokuapp.com/',               description: 'PHP is the Nickelback of programming languages.'                                        }
  - { label: PHP TestFest,              icon: fas fa-code,              url: 'https://phptestfest.org/',                            description: 'PHP TestFest aims to improve the code coverage of the test suite for PHP.'              }
  - { label: PHP.UserGroup,             icon: fas fa-users,             url: 'http://php.ug/',                                      description: 'An international meeting-point for the PHP-Community.'                                  }
  - { label: PHP Women,                 icon: fas fa-venus,             url: 'http://phpwomen.org/',                                description: 'An inclusive & global network providing support within the PHP community.'              }
  - { label: PHP Mentoring,             icon: fas fa-graduation-cap,    url: 'https://php-mentoring.org/',                          description: 'Focus on creating networks of skilled developers from all walks of life.'               }
  - { label: OSMI,                      icon: far fa-handshake,         url: 'https://osmihelp.org/',                               description: 'Changing how we talk about mental health in the tech community.'                        }
  - { label: Static Analysis Tools,     icon: fas fa-list-ol,           url: 'https://github.com/exakat/php-static-analysis-tools', description: 'A curated list of static analysis tools for PHP.'                                       }

metadata:
  authors:      { label: Author(s),           icon: far fa-user,                                                                                                      }
  companies:    { label: Company,             icon: far fa-building,                                                                                                  }
  website:      { label: Website,             icon: fas fa-globe,         button: true,   button-class: btn-website                                                   }
  license:      { label: License,             icon: far fa-id-card,                                                                                                   }
  terms:        { label: Terms (Of Service),  icon: far fa-thumbs-up,     button: true,   button-class: btn-terms                                                     }
  wiki:         { label: Wiki,                icon: far fa-list-alt,      button: true,   button-class: btn-wiki                                                      }
  docs:         { label: Documentation,       icon: fas fa-info,          button: true,   button-class: btn-docs                                                      }
  demo:         { label: Demo,                icon: fas fa-desktop,       button: true,   button-class: btn-demo                                                      }
  github:       { label: GitHub,              icon: fab fa-github,        button: true,   button-class: btn-github,     url-prefix: 'https://github.com/'             }
  packagist:    { label: Packagist,           icon: far fa-compass,       button: true,   button-class: btn-packagist,  url-prefix: 'https://packagist.org/packages/' }
  dockerhub:    { label: DockerHub,           icon: fab fa-docker,        button: true,   button-class: btn-dockerhub,  url-prefix: 'https://hub.docker.com/r/'       }
  dependencies: { label: Dependencies,        icon: far fa-check-square,                                                                                              }

project_keys:
  - path
  - output
  - id
  - url
  - content
  - collection
  - excerpt
  - relative_path
  - draft
  - categories

  - layout
  - title
  - tags
  - authors
  - companies
  - website
  - license
  - terms
  - wiki               
  - docs
  - demo
  - github
  - packagist
  - dockerhub
  - dependencies
  - composer
  - composer-dev
  - composer-global
  - gem
  - git
  - phar

  - slug
  - ext
  - date


