# GitHub Pages
### ### ### ### ### ###

github: [metadata]                                    # set by GitHub Pages, can be overwritten
#lsi: false                                           # set by GitHub Pages, cannot be changed
#safe: true                                           # set by GitHub Pages, cannot be changed
#source: [your repo's top level directory]            # set by GitHub Pages, cannot be changed
#incremental: false                                   # set by GitHub Pages, cannot be changed
#highlighter: rouge                                   # set by GitHub Pages, cannot be changed
#gist:
#  noscript: false                                    # set by GitHub Pages, cannot be changed
kramdown:
  input: GFM                                          # set by GitHub Pages, can be overwritten
  hard_wrap: false                                    # set by GitHub Pages, can be overwritten
#  math_engine: mathjax                               # set by GitHub Pages, cannot be changed
  smart_quotes: ["apos", "apos", "quot", "quot"]      # turn off smart quotes
plugins:
  - jekyll-coffeescript                               # set by GitHub Pages, can be overwritten
  - jekyll-paginate                                   # set by GitHub Pages, can be overwritten
  - jekyll-seo-tag                                    # add seo tag
  - jekyll-sitemap                                    # add sitemap
  - jekyll-feed                                       # add rss feed

# Jekyll settings
### ### ### ### ### ###

encoding: utf-8
strict_front_matter: true
excerpt_separator: <!--more-->
exclude:
  - CNAME
  - docker-compose.yml
  - LICENSE
  - README.md
  - _projects/_draft.md
webrick:
  headers:
    X-Powered-By: PHP/6

# PHP QA
### ### ### ### ### ###

author: Bart Reunes   
name: PHP Quality Assurance
description: A community managed website about PHP Quality Assurance
url: https://phpqa.io
lang: en_US

title: PHP Quality Assurance
subtitle: Looking for ways to make your PHP code even better? Find the projects that can help you!

google_analytics: UA-100482560-1

webmaster_verifications:
  google: JITUi06ndisXmR9iEyEtJWMR7ZaYF8ycjhUTUvubBHk
  bing: 3CB22B04462C70550E27942615BF8C01

collections:

  pages:
    output: true
    permalink: /:title.html

  projects:
    output: true
    permalink: /:collection/:title.html

  posts:
    output: true
    permalink: /:collection/:categories/:year/:month/:day/:title.html

  websites:
    output: false

navigation:
  projects:     { label: Projects,      icon: fas fa-cogs,              url: /index.html                                  }
  community:    { label: Websites,      icon: fas fa-map-signs,         url: /websites.html                               }
  about:        { label: About,         icon: fas fa-info-circle,       url: /about.html                                  }
  news:         { label: News,          icon: fas fa-list-alt,          url: /news.html                                   }
  #usage:        { label: Usage,         icon: fas fa-magic,             url: /usage.html                                  }
  github:       { label: GitHub,        icon: fab fa-github,            url: 'https://github.com/phpqa/phpqa.github.io'   }
  dockerhub:    { label: DockerHub,     icon: fab fa-docker,            url: 'https://hub.docker.com/u/phpqa/'            }
  contributing: { label: Contributing,  icon: fas fa-sign-language,     url: /contributing.html                           }

project_keys:
  - path
  - output
  - id
  - url
  - content
  - collection
  - excerpt
  - relative_path
  - draft
  - categories

  - layout
  - title
  - order
  - tags
  - authors
  - companies
  - website
  - license
  - terms
  - wiki               
  - docs
  - demo
  - github
  - packagist
  - dockerhub
  - dependencies
  - composer
  - composer-dev
  - composer-global
  - gem
  - git
  - phar

  - slug
  - ext
  - date


