version: '3.1'

services:

    jekyll:
        image: jekyll/jekyll:pages
        command: jekyll serve
        environment:
            - POLLING=true
        volumes:
            - app:/srv/jekyll
        ports:
            - "4000:4000"
        networks:
            jekyll:

networks:
    jekyll:

volumes:
    app:
        driver: local # https://github.com/moby/moby/issues/32217#issuecomment-290716758
        driver_opts:
            o: bind
            type: none
            device: $PWD

